version: '(build)'
branches:
  only:
    - master

platform:
  - x64

environment:
  matrix:
    - generator: "Visual Studio 14 2015 Win64"
      config: Debug
    - generator: "Visual Studio 14 2015 Win64"
      config: Release

matrix:
  fast_finish: true

init:
  - cmd: |-
      cmake --version

  - cmd: |-
      mkdir .\builds
      cd builds
      git clone https://github.com/glfw/glfw.git .\glfw
      mkdir .\glfw\build
      cd glfw\build
      cmake -DBUILD_SHARED_LIBS=ON .. -G %generator%
      cmake --build . --config %config% --target install

before_build:
  - cmd: |-
      mkdir .\build
      cd build
      cmake .. -G %generator% -DEXAMPLES:BOOL=ON

build:
  project: c:\projects\SolusEngine\build\SolusEngine.sln
  verbosity: minimal
  parallel: true

