version: '(build)'
branches:
  only:
    - master

platform:
  - x64

environment:
  matrix:
    - generator: "Visual Studio 14 2015 Win64"
      config: Debug
    - generator: "Visual Studio 14 2015 Win64"
      config: Release

matrix:
  fast_finish: true

init:
  - cmd: |-
      mkdir C:\projects\deps
      cmake --version

  - cmd: |-
      cd c:\projects\deps
      git clone https://github.com/g-truc/glm.git
      mkdir .\glm\build
      cd glm\build
      cmake -DGLM_TEST_ENABLE_CXX_11=ON .. -G "%generator%"
      cmake --build . --config %config% --target install
      set "PATH=C:\Program Files\GLM\bin;%PATH%"

  - cmd: |-
      cd c:\projects\deps
      git clone https://github.com/KhronosGroup/glslang.git
      mkdir .\glslang\build
      cd glslang\build
      cmake .. -G "%generator%"
      cmake --build . --config %config% --target install
      set "PATH=C:\Program Files\glslang\bin;%PATH%"

  - cmd: |-
      cd c:\projects\deps
      git clone https://github.com/KhronosGroup/Vulkan-Headers.git
      mkdir .\Vulkan-Headers\build
      cd Vulkan-Headers\build
      cmake .. -G "%generator%"
      cmake --build . --config %config% --target install

  - cmd: |-
      cd c:\projects\ 
      git clone https://github.com/glfw/glfw.git
      mkdir .\glfw\build
      cd glfw\build
      cmake -DBUILD_SHARED_LIBS=ON .. -G "%generator%"
      cmake --build . --config %config% --target install

before_build:
  - cmd: |-
      mkdir .\build
      cd build
      cmake .. -G "%generator%" -DEXAMPLES:BOOL=ON

build:
  project: c:\projects\SolusEngine\build\SolusEngine.sln
  verbosity: minimal
  parallel: true

