version: '(build)'
branches:
  only:
    - master

shallow_clone: true

platform:
  - x64

environment:
  DOXYGEN_ROOT: C:\projects\doxygeni
  DOXYGEN_EXE: C:\projects\doxygen\Doxygen.1.8.13\tools\doxygen.exe
  PYTHON: "C:\\Python33-x64"

 matrix: 
    - generator: "Visual Studio 14 2015 Win64"
      config: Debug
    - generator: "Visual Studio 14 2015 Win64"
      config: Release

matrix:
  fast_finish: true

init:
  - cmd: |-
      mkdir C:\projects\deps
      cmake --version

  - cmd: |-
      cd c:\projects\deps
      git clone https://github.com/g-truc/glm.git
      mkdir .\glm\build
      cd glm\build
      cmake -DGLM_TEST_ENABLE_CXX_11=ON .. -G "%generator%"
      cmake --build . --config %config% --target install
      set "PATH=C:\Program Files\GLM\bin;%PATH%"

  - cmd: |-
      cd c:\projects\deps
      git clone https://github.com/KhronosGroup/glslang.git
      mkdir .\glslang\build
      cd glslang\build
      cmake .. -G "%generator%"
      cmake --build . --config %config% --target install
      set "PATH=C:\Program Files\glslang\bin;%PATH%"

  - cmd: |-
      cd c:\projects\deps
      git clone https://github.com/KhronosGroup/SPIRV-Tools.git
      cd SPIRV-Tools
      git clone https://github.com/KhronosGroup/SPIRV-Headers.git ./external/spirv-headers
      mkdir build
      cd build
      cmake -DSPIRV_WERROR=OFF ..
      cmake --build . --config %config% --target install

  - cmd: |-
      cd c:\projects\deps
      git clone https://github.com/KhronosGroup/Vulkan-Headers.git
      mkdir .\Vulkan-Headers\build
      cd Vulkan-Headers\build
      cmake .. -G "%generator%"
      cmake --build . --config %config% --target install

  - cmd: |- 
      cd c:\projects\deps
      git clone https://github.com/KhronosGroup/Vulkan-Loader.git
      cd Vulkan-Loader
      mkdir build
      cd build
      cmake -DVULKAN_HEADERS_INSTALL_DIR="C:/projects/deps/Vulkan-Headers/build/install/include/vulkan" ..
      cmake --build . --config %config% --target install

  - cmd: |-
      cd c:\projects\deps
      git clone https://github.com/KhronosGroup/Vulkan-ValidationLayers.git
      cd Vulkan-ValidationLayers
      sed  -i -e '/#include/i#include <cmath>\n' layers/parameter_validation_utils.cpp
      mkdir build
      cd build
      cmake -DVULKAN_HEADERS_INSTALL_DIR="C:/projects/deps/Vulkan-Headers/build/install/include/vulkan" -DGLSLANG_INSTALL_DIR="C:\Program Files\glslang" ..
      cmake --build . --config %config% --target install
  
  - cmd: |-
      cd c:\projects\deps
      git clone https://github.com/KhronosGroup/Vulkan-Tools.git
      cd Vulkan-Tools
      mkdir build
      cd build
      cmake ..
      cmake --build . --config %config% --target install

  - cmd: |-
      cd c:\projects\ 
      git clone https://github.com/glfw/glfw.git
      mkdir .\glfw\build
      cd glfw\build
      cmake -DBUILD_SHARED_LIBS=ON .. -G "%generator%"
      cmake --build . --config %config% --target install

before_build:
  - cmd: |-
      mkdir .\build
      cd build
      cmake .. -G "%generator%" -DEXAMPLES:BOOL=ON -

build:
  project: c:\projects\SolusEngine\build\SolusEngine.sln
  verbosity: minimal
  parallel: true

